services:
  - type: web
    name: sudoku-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://sudoku-server-tqb6.onrender.com/api